# Generated by Django 2.2.17 on 2021-03-12 12:43

from django.db import migrations


def create_groups(apps, schema_monitor):
    Group = apps.get_model("auth", "Group")
    Group.objects.bulk_create([
        Group(name='Staff'),
        Group(name='Seller'),
    ])


def remove_groups(apps, schema_monitor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=['Staff', 'Seller']).delete()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_groups, remove_groups)
    ]
