# Generated by Django 2.2.17 on 2021-04-01 11:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('swapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 1, 11, 16, 42, 562794, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 1, 11, 16, 42, 561790, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 1, 11, 16, 42, 561790, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 1, 11, 16, 42, 561790, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 1, 11, 16, 42, 561790, tzinfo=utc)),
        ),
    ]
