# Generated by Django 2.2.17 on 2021-03-31 23:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('swapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 31, 23, 24, 0, 563313, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 31, 23, 24, 0, 563313, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 31, 23, 24, 0, 563313, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 31, 23, 24, 0, 563313, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 31, 23, 24, 0, 563313, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='item',
            name='sold_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='swapp.Checkout'),
        ),
    ]
