# Generated by Django 2.2.17 on 2021-03-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapp', '0003_auto_20210317_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='picture',
            field=models.ImageField(blank=True, upload_to='announcements'),
        ),
        migrations.AlterField(
            model_name='item',
            name='checked',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ImageField(blank=True, upload_to='item_pictures'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sold',
            field=models.BooleanField(),
        ),
    ]
